baseURL = 'https://NoDreamboat.github.io/'
languageCode = 'zh-cn'
title = 'Divergence 1.048596' # 博客标题
theme = 'PaperMod'

[params.assets]
  favicon = "<link /favicon.ico>" # 下面会说

[params]
    [params.profileMode]
    enabled = true
    imageUrl = "avatar.jpg"     # 对应 static/avatar.jpg
    imageTitle = "LabMem 001"
    imageWidth = 120
    imageHeight = 120

  # 默认深色模式，符合黑客/S;G氛围
  defaultTheme = 'dark'

  # 强调色，这里建议不要用默认的，虽然PaperMod不支持直接改hex，
  # 但我们可以通过后续的CSS来把高亮色改成辉光管的橙色。

  # 首页配置
  [params.homeInfoParams]
    Title = "Welcome to Lab Member No.001's Archive"
    Content = """
    这里是世界线收束的观测点。

    > “那并不是幻视。不管是那家伙的死，还是其他的什么，我确实全都清楚地记得。”

    记录 Linux 折腾笔记、软件测试心得，以及前往日本的计划。
    **El Psy Kongroo.**
    """

  # 社交链接 (替换成你的)
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/NoDreamboat"
  [[params.socialIcons]]
    name = "email"
    url = "mailto:2363989669@qq.com"

  # 顶部导航栏 (关键！添加归档和搜索)
  [menu]
  [[menu.main]]
    identifier = "archives"
    name = "Timeline"  # 把“归档”改成“时间线”，更有S;G味
    url = "/archives/"
    weight = 10
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 20
  [[menu.main]]
    identifier = "tags"
    name = "Divergence" # 把“标签”改成“变动率”
    url = "/tags/"
    weight = 30
